---
include:
  - project: shore/ci-stuff
    file: templates/pre-commit.yml

build:
  stage: deploy
  tags: ["ns4.shore.co.il"]
  only: ["nimrod"]
  script:
    - cid="$(basename $(cat /proc/1/cpuset))"
    - docker pull registry.shore.co.il/presentation
    - >-
      docker run
      --rm
      --volumes-from "$cid"
      --volume "/var/www/www.shore.co.il/resume:/builds/nimrod/resume/output"
      --workdir "$PWD"
      registry.shore.co.il/presentation
      make
      DESTDIR=output
      --jobs=4
      --keep-going
