---
include:
  - project: shore/ci-templates
    file: templates/pre-commit.yml

build:
  stage: deploy
  tags: ["host01.shore.co.il"]
  only: ["nimrod"]
  script:
    - cid="$(basename $(cat /proc/1/cpuset))"
    - docker pull adarnimrod/presentation
    - >-
      docker run
      --rm
      --volumes-from "$cid"
      --volume "/var/www/www.shore.co.il/resume:/builds/nimrod/resume/output"
      --workdir "$PWD"
      adarnimrod/presentation
      make
      DESTDIR=output
      --jobs=4
      --keep-going
